### ISSUE TITLE
Feature request: add a screen always on switch widget 

### ISSUE THREAD

**Issue by brunetton** [asdoi/QuickTiles#1]
Hi, thanks for this amazing open source project! I'm using it for a while now and the only little thing I miss is the availability to have a switch that prevents switch off and screen lock. 
Something like the existing screen timeout, but that remember the actual timeout to set it back when disabling "always on". 
Example :

- my screen timeout is set to 1 minute 
- I want to let it be infinite so I click on my "always on" widget 
- the screen timeout is disabled (set to infinity) 
- later I want it back to one minute (previous non infinity value), so I click again on my widget and the screen timeout is set to 1 minute again, like before disabling timeout 

I'm aware of some widgets in Play Store that does this but as far as I know, there's no open-source way of doing it. 

What do you think about? 

Thanks!

**Comment by asdoi** [comment]
Hi @brunetton  
This already available.
In the development section there is a "keep screen on" tile which does exactly what you want, if you set the connection type to "connected to any power source".
Maybe I should move it to a more prominent position.

**Comment by brunetton** [comment]
Thanks ! This is a great new !

> Maybe I should move it to a more prominent position.

Indeed, I wouldn't excepted to find it on "development" tools, as I mainly use it while cooking :laughing:, and most of display-related options are placed in the "system utilities" section. For me this is the "friend" of "screen timeout" so I would put them together. 
Anyway, thanks a lot :)

**Comment by asdoi** [comment]
Good idea, I moved it below the "screen timeout" setting.
